Repository luxonis/depthai, pull requests merged in 2020-11, with the labels that each got.

#260 Fix crash on 2nd device object delete
  requirements.txt
Labels: Gen1

#262 Fix tests
  depthai_demo.py
  depthai_helpers/cli_utils.py
  depthai_helpers/version_check.py
  integration_test.py
  requirements.txt
  run_tests.py
  tests/repeat_test.py
  tests/test_cli_utils.py
  tests/test_executor.py
  tests/tests_runner.py
  testsFunctional/runFunctionalTests.py
  testsFunctional/test_meta_d2h.py
  testsFunctional/test_object_tracker.py
  testsFunctional/test_video.py
Labels: Gen1, enhancement

#261 Update log system information script
  install_requirements.py
  install_requirements.sh
  log_system_information.py
  log_system_information.sh
  package/create_package.sh
Labels: enhancement

#265 Add better error handling in model downloader & migrate to new BlobConverter
  model_compiler/model_compiler.py
Labels: Gen1, enhancement

#268 Python3.9 support
  .gitignore
  depthai_helpers/arg_manager.py
  depthai_helpers/version_check.py
  install_requirements.py
  log_system_information.py
  requirements.txt
Labels: Gen1, enhancement

#271 Hotfix for python3.6 failure w/ model downloader
  model_compiler/model_compiler.py
Labels: bug

#279 RGB camera fixes + key controls for manual focus/exposure
  depthai_demo.py
  requirements.txt
Labels: Gen1, bug, enhancement
